# Generated by Django 4.2 on 2025-09-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(help_text="A personal name for this source, e.g., 'My Android Phone'", max_length=100),
        ),
        migrations.AlterField(
            model_name='jsonurldatasource',
            name='url',
            field=models.URLField(help_text='The URL where the JSON data can be fetched', max_length=500),
        ),
    ]
