# Generated by Django 4.2 on 2025-09-30 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0002_alter_datasource_name_alter_jsonurldatasource_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwareDataSource',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_sources.datasource')),
                ('device_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data_sources.datasource',),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(help_text='A personal name for this source', max_length=100),
        ),
    ]
