# Generated by Django 4.2 on 2025-09-30 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0003_awaredatasource_alter_datasource_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awaredatasource',
            name='device_id',
        ),
        migrations.AddField(
            model_name='awaredatasource',
            name='config_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='awaredatasource',
            name='device_label',
            field=models.CharField(default=uuid.uuid4, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='awaredatasource',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('active', 'Active')], default='pending', max_length=20),
        ),
    ]
