# Generated by Django 4.2 on 2025-09-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0004_remove_awaredatasource_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awaredatasource',
            name='aware_device_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
