# Generated by Django 4.2 on 2025-10-03 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0005_awaredatasource_aware_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonurldatasource',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
