# Generated by Django 4.2 on 2025-10-10 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0006_jsonurldatasource_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awaredatasource',
            name='aware_device_id',
        ),
        migrations.RemoveField(
            model_name='awaredatasource',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jsonurldatasource',
            name='device_id',
        ),
        migrations.AddField(
            model_name='datasource',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('active', 'Active')], default='pending', max_length=20),
        ),
    ]
