# Generated by Django 4.2 on 2025-10-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0007_remove_awaredatasource_aware_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleTakeoutDataSource',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_sources.datasource')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='takeout_uploads/')),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded, pending processing'), ('processing', 'Processing'), ('processed', 'Processed successfully'), ('error', 'Error during processing')], default='uploaded', max_length=20)),
                ('processing_log', models.TextField(blank=True, help_text='Log messages from the processing task.')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data_sources.datasource',),
        ),
    ]
