# Generated by Django 4.2 on 2025-10-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0008_googletakeoutdatasource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleTakeoutDataSource',
            new_name='GooglePortabilityDataSource',
        ),
    ]
