# Generated by Django 4.2 on 2025-10-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0009_rename_googletakeoutdatasource_googleportabilitydatasource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='access_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='downloaded_file',
            field=models.FileField(blank=True, null=True, upload_to='portability_downloads/'),
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='oauth_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
