# Generated by Django 4.2 on 2025-10-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0010_remove_googleportabilitydatasource_uploaded_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='downloaded_file',
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='data_job_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='downloaded_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='googleportabilitydatasource',
            name='processing_status',
            field=models.CharField(choices=[('authorized', 'Authorized, waiting for download'), ('processing', 'Processing'), ('processed', 'Processed successfully'), ('error', 'Error during processing')], default='uploaded', max_length=20),
        ),
    ]
