# Generated by Django 4.2 on 2025-11-06 12:17

from django.db import migrations, models
import uuid


def assign_config_tokens(apps, schema_editor):
    DataSource = apps.get_model('data_sources', 'DataSource')
    for ds in DataSource.objects.all():
        ds.config_token = uuid.uuid4()
        ds.save(update_fields=['config_token'])

class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0011_remove_googleportabilitydatasource_downloaded_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awaredatasource',
            name='config_token',
        ),
        migrations.AddField(
            model_name='datasource',
            name='config_token',
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
        migrations.RunPython(assign_config_tokens, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='datasource',
            name='config_token',
            field=models.UUIDField(editable=False, unique=True, null=False),
        ),
    ]
