# Generated by Django 4.2 on 2025-11-06 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0012_remove_awaredatasource_config_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='oauth_state',
        ),
        migrations.AddField(
            model_name='datasource',
            name='oauth_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='config_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
