# Generated by Django 4.2 on 2025-11-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0013_remove_googleportabilitydatasource_oauth_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='googleportabilitydatasource',
            name='access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
