# Generated by Django 4.2 on 2025-11-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0014_remove_googleportabilitydatasource_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
