# Generated by Django 4.2 on 2025-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0015_googleportabilitydatasource_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('active', 'Active')], default='pending', max_length=20),
        ),
    ]
