# Generated by Django 4.2 on 2025-11-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0016_alter_datasource_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='file_status',
            field=models.JSONField(blank=True, default=dict, help_text="Maps filepath to {'processed': bool, 'processed_at': timestamp}"),
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='job_status',
            field=models.JSONField(blank=True, default=dict, help_text="Maps job_id to {'completed': bool, 'downloaded_at': timestamp, 'state': job_state}"),
        ),
    ]
