# Generated by Django 4.2 on 2025-11-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0017_googleportabilitydatasource_file_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokPortabilityDataSource',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_sources.datasource')),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('tiktok_user_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('processing_status', models.CharField(choices=[('authorized', 'Authorized, waiting for data'), ('data_requested', 'Data portability request submitted'), ('processing', 'Processing'), ('processed', 'Processed successfully'), ('error', 'Error during processing')], default='authorized', max_length=20)),
                ('processing_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data_sources.datasource',),
        ),
    ]
