# Generated by Django 4.2 on 2025-11-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0018_tiktokportabilitydatasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokportabilitydatasource',
            name='code_verifier',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
