# Generated by Django 4.2 on 2026-01-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0019_tiktokportabilitydatasource_code_verifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={},
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('device_id', 'profile'), name='unique_device_per_user'),
        ),
    ]
