# Generated by Django 4.2 on 2026-01-14 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0020_alter_datasource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
