# Generated by Django 4.2 on 2026-01-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0021_alter_datasource_device_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveConstraint(
            model_name='datasource',
            name='unique_device_per_user',
        ),
    ]
