# Generated by Django 4.2 on 2026-02-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0022_alter_datasource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='data_type_status',
            field=models.JSONField(blank=True, default=dict, help_text="Maps data_type to {'received': bool, 'received_at': timestamp}"),
        ),
    ]
