# Generated by Django 4.2 on 2026-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0023_googleportabilitydatasource_data_type_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='data_job_ids',
        ),
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='downloaded_files',
        ),
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='file_status',
        ),
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='google_user_id',
        ),
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='job_status',
        ),
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='token_expiry',
        ),
        migrations.RemoveField(
            model_name='tiktokportabilitydatasource',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='tiktokportabilitydatasource',
            name='code_verifier',
        ),
        migrations.RemoveField(
            model_name='tiktokportabilitydatasource',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='tiktokportabilitydatasource',
            name='tiktok_user_id',
        ),
        migrations.RemoveField(
            model_name='tiktokportabilitydatasource',
            name='token_expiry',
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='donation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='donation_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktokportabilitydatasource',
            name='donation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktokportabilitydatasource',
            name='donation_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleportabilitydatasource',
            name='data_type_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='googleportabilitydatasource',
            name='processing_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='googleportabilitydatasource',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized, waiting for download'), ('processing', 'Processing'), ('processed', 'Processed successfully'), ('error', 'Error during processing')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tiktokportabilitydatasource',
            name='processing_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tiktokportabilitydatasource',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized, waiting for data'), ('processing', 'Processing'), ('processed', 'Processed successfully'), ('error', 'Error during processing')], default='pending', max_length=20),
        ),
    ]
