# Generated by Django 4.2 on 2026-04-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0024_remove_googleportabilitydatasource_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='data_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='data_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleportabilitydatasource',
            name='requested_data_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tiktokportabilitydatasource',
            name='data_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktokportabilitydatasource',
            name='data_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktokportabilitydatasource',
            name='requested_data_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
