# Generated by Django 4.2 on 2026-04-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0025_googleportabilitydatasource_data_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='requested_data_types',
        ),
        migrations.RemoveField(
            model_name='tiktokportabilitydatasource',
            name='requested_data_types',
        ),
    ]
