# Generated by Django 4.2 on 2026-04-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0026_remove_googleportabilitydatasource_requested_data_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='data_end_date',
        ),
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='data_start_date',
        ),
        migrations.RemoveField(
            model_name='tiktokportabilitydatasource',
            name='data_end_date',
        ),
        migrations.RemoveField(
            model_name='tiktokportabilitydatasource',
            name='data_start_date',
        ),
    ]
