# Generated by Django 4.2 on 2025-10-11 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('data_sources', '0007_remove_awaredatasource_aware_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('config_url', models.URLField(help_text='URL for fetching study configuration', max_length=500)),
                ('researchers', models.ManyToManyField(limit_choices_to={'user_type': 'researcher'}, related_name='studies', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
                ('revocation_date', models.DateTimeField(blank=True, null=True)),
                ('data_sources', models.ManyToManyField(related_name='consents', to='data_sources.datasource')),
                ('participant', models.ForeignKey(limit_choices_to={'user_type': 'participant'}, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='users.profile')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='studies.study')),
            ],
            options={
                'unique_together': {('participant', 'study')},
            },
        ),
    ]
