# Generated by Django 4.2 on 2025-10-13 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0007_remove_awaredatasource_aware_device_id_and_more'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consent',
            name='data_sources',
        ),
        migrations.AddField(
            model_name='consent',
            name='data_source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='data_sources.datasource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consent',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='required_data_sources',
            field=models.JSONField(default=list, help_text='List of required data source types'),
        ),
        migrations.AddField(
            model_name='study',
            name='source_configurations',
            field=models.JSONField(default=dict, help_text="Maps source types to config filenames, e.g., {'AwareDataSource': 'aware_config.json'}"),
        ),
    ]
