# Generated by Django 4.2 on 2025-10-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_remove_consent_data_sources_consent_data_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='optional_data_sources',
            field=models.JSONField(blank=True, default=list, help_text="List of optional source types, e.g., ['JsonUrlDataSource']"),
        ),
        migrations.AlterField(
            model_name='study',
            name='required_data_sources',
            field=models.JSONField(blank=True, default=list, help_text="List of required source types, e.g., ['AwareDataSource']"),
        ),
    ]
