# Generated by Django 4.2 on 2025-10-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_study_optional_data_sources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='source_configurations',
        ),
    ]
