# Generated by Django 4.2 on 2025-10-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('studies', '0004_remove_study_source_configurations'),
    ]

    operations = [
        # Logic moved to studies/apps.py to avoid race conditions
    ]
