# Generated by Django 4.2 on 2025-10-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0007_remove_awaredatasource_aware_device_id_and_more'),
        ('studies', '0005_create_researcher_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consent',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='consent',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='data_sources.datasource'),
        ),
    ]
