# Generated by Django 4.2 on 2025-10-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_alter_consent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consent',
            name='source_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
