# Generated by Django 4.2 on 2025-10-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_consent_is_optional_consent_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='consent_text_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
