# Generated by Django 4.2 on 2025-10-27 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0011_remove_googleportabilitydatasource_downloaded_file_and_more'),
        ('studies', '0009_researcher_token_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='data_sources.datasource'),
        ),
    ]
