# Generated by Django 4.2 on 2025-10-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_alter_consent_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='source_configurations',
            field=models.JSONField(blank=True, default=dict, help_text='List of source configuration files for the study'),
        ),
    ]
