# Generated by Django 4.2 on 2025-10-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_study_source_configurations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='source_configurations',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of source configuration files for the study'),
        ),
    ]
