# Generated by Django 4.2 on 2025-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_alter_study_source_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='domain',
            field=models.CharField(blank=True, help_text="Domain name of the study's landing page", max_length=200, null=True, unique=True),
        ),
    ]
