# Generated by Django 4.2 on 2026-02-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_study_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
