# Generated by Django 4.2 on 2026-02-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0014_alter_consent_consent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='data_start',
            field=models.DateTimeField(blank=True, help_text='Start of the data collection period. May predate consent_date.', null=True),
        ),
    ]
