# Generated by Django 4.2 on 2026-03-09 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('studies', '0015_consent_data_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('participant', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'participant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_participations', to='users.profile')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='studies.study')),
            ],
            options={
                'unique_together': {('participant', 'study')},
            },
        ),
        migrations.AddField(
            model_name='consent',
            name='study_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='studies.studyparticipant'),
        ),
    ]
