# Generated by Django 4.2 on 2026-03-09 11:42

from django.db import migrations


def backfill_study_participants(apps, schema_editor):
    Consent = apps.get_model('studies', 'Consent')
    StudyParticipant = apps.get_model('studies', 'StudyParticipant')

    pairs = (
        Consent.objects.filter(study_participant__isnull=True)
        .values_list('participant_id', 'study_id')
        .distinct()
    )
    for participant_id, study_id in pairs:
        if participant_id is None:
            continue
        sp, _ = StudyParticipant.objects.get_or_create(
            participant_id=participant_id,
            study_id=study_id,
        )
        Consent.objects.filter(
            participant_id=participant_id,
            study_id=study_id,
            study_participant__isnull=True,
        ).update(study_participant=sp)


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_studyparticipant_consent_study_participant'),
    ]

    operations = [
        migrations.RunPython(backfill_study_participants, migrations.RunPython.noop),
    ]
