# Generated by Django 4.2 on 2026-03-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('studies', '0017_backfill_study_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='participant',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'participant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='users.profile'),
        ),
    ]
