# Generated by Django 4.2 on 2026-03-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_alter_consent_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Email of the contact person for this study', max_length=254),
        ),
        migrations.AddField(
            model_name='study',
            name='contact_name',
            field=models.CharField(blank=True, default='', help_text='Name of the contact person for this study', max_length=200),
        ),
    ]
