# Generated by Django 4.2 on 2026-03-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0019_study_contact_email_study_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='repo_branch',
            field=models.CharField(blank=True, default='main', help_text='Branch name in the config repository (default: main)', max_length=100),
        ),
    ]
