# Generated by Django 4.2 on 2026-03-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0020_study_repo_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='domain',
        ),
    ]
