# Generated by Django 4.2 on 2026-03-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0022_convert_source_configurations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='optional_data_sources',
        ),
        migrations.RemoveField(
            model_name='study',
            name='required_data_sources',
        ),
        migrations.AlterField(
            model_name='study',
            name='source_configurations',
            field=models.JSONField(blank=True, default=dict, help_text='Dict mapping source type names to their configuration. Each entry should have at minimum a \'status\' key (\'required\' or \'optional\'). Optional keys: \'data_start\', \'data_end\' (ISO datetime strings), \'config_file\'. Example: {"AwareDataSource": {"status": "required", "data_start": "2024-01-01T00:00:00"}}'),
        ),
    ]
